<?php
namespace WebSocket\Exception;
/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-10-19 at 20:38:24.
 */
class ConnectionExceptionTest extends \PHPUnit_Framework_TestCase {

    /**
     * @expectedException WebSocket\Exception\ConnectionException
     */
   public function testConnectionException() {
       throw new \WebSocket\Exception\ConnectionException;
   }
}
